### ISSUE TITLE
some issues when running the phase2.py on CIFAR-100

### ISSUE THREAD

**Issue by Pengfight** [haochenglouis/cores#1]
When I run the phase2.py on CIFAR-100, the error happened.

```
Traceback (most recent call last):
  File "phase2.py", line 287, in <module>
    result = train_and_eval(args.tag, args.dataroot, resume=args.resume, save_path=args.save, only_eval=args.only_eval, unsupervised=args.unsupervised, devices=args.gpu)
  File "phase2.py", line 140, in train_and_eval
    trainloader, unsuploader, testloader = get_dataloaders(C.get()['dataset'], C.get()['batch'], C.get()['batch_unsup'], 
  File "/home/cuipeng/cores/phase2/data.py", line 156, in get_dataloaders
    sampler=StratifiedSampler(trainset.targets), drop_last=True)
AttributeError: 'Subset' object has no attribute 'targets'
```

**Comment by haochenglouis** [comment]
The problem may come from Line 133 in phase2.py. I think you did not input the correct path of 'unsup_idx'.
